apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: gpu-operator
data:
  a100-40gb: |-
    version: v1
    flags:
      migStrategy: mixed
  a100-40gb-1: |-
    version: v1
    flags:
      migStrategy: mixed

