apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: quay.io/project-codeflare/busybox:1.36
    command: ["sh", "-c", "sleep 5"]
    resources:
      limits:
        nvidia.com/mig-1g.5gb: 1
