apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.27.11"
apiServer:
  extraArgs:
    runtime-config: "resource.k8s.io/v1alpha2=true"
    feature-gates: "DynamicResourceAllocation=true"
scheduler:
  extraArgs:
    v: "1"
    feature-gates: "DynamicResourceAllocation=true"
controllerManager:
  extraArgs:
    v: "1"
    feature-gates: "DynamicResourceAllocation=true"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - token: abcdef.0123456789abcdef
nodeRegistration:
  kubeletExtraArgs:
    v: "1"
    feature-gates: "DynamicResourceAllocation=true"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  tlsBootstrapToken: abcdef.0123456789abcdef 
nodeRegistration:
  kubeletExtraArgs:
    v: "1"
    feature-gates: "DynamicResourceAllocation=true"
