apiVersion: v1
kind: Pod
metadata:
  name: small
spec:
  restartPolicy: Never
  containers:
    - name: vectoradd
      image: "quay.io/tardieu/vectoradd:0.1.0"
      resources:
        claims:
        - name: mig-1g-5gb-0
        - name: mig-1g-5gb-1
  resourceClaims:
    - name: mig-1g-5gb-0
      source:
        resourceClaimTemplateName: mig-1g.5gb
    - name: mig-1g-5gb-1
      source:
        resourceClaimTemplateName: mig-1g.5gb
---
apiVersion: v1
kind: Pod
metadata:
  name: large
spec:
  restartPolicy: Never
  containers:
    - name: vectoradd
      image: "quay.io/tardieu/vectoradd:0.1.0"
      resources:
        claims:
        - name: mig-2g-10gb
  resourceClaims:
    - name: mig-2g-10gb
      source:
        resourceClaimTemplateName: mig-2g.10gb
---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: MigDeviceClaimParameters
metadata:
  name: mig-1g.5gb
spec:
  profile: 1g.5gb
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: mig-1g.5gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: gpu.resource.nvidia.com
      kind: MigDeviceClaimParameters
      name: mig-1g.5gb
---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: MigDeviceClaimParameters
metadata:
  name: mig-2g.10gb
spec:
  profile: 2g.10gb
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: mig-2g.10gb
spec:
  spec:
    resourceClassName: gpu.nvidia.com
    parametersRef:
      apiGroup: gpu.resource.nvidia.com
      kind: MigDeviceClaimParameters
      name: mig-2g.10gb
