apiVersion: v1
kind: Pod
metadata:
  name: small
spec:
  restartPolicy: Never
  containers:
    - name: vectoradd
      image: "quay.io/tardieu/vectoradd:0.1.0"
      resources:
        limits:
          nvidia.com/mig-1g.5gb: 2 # request 2 slices for demo purposes
---
apiVersion: v1
kind: Pod
metadata:
  name: large
spec:
  restartPolicy: Never
  containers:
    - name: vectoradd
      image: "quay.io/tardieu/vectoradd:0.1.0"
      resources:
        limits:
          nvidia.com/mig-2g.10gb: 1
